### ISSUE TITLE
Module crash if gzip enable

### ISSUE THREAD

**Issue by vcazsdk** [RekGRpth/ngx_http_upstream_queue_module#3] opened 2024-09-20 22:42 UTC
Hi,
Thank you for sharing this module.
I try to used it but the module crash on first connexion :
```
2024/09/20 21:51:28 [debug] 45#45: *24 ngx_http_upstream_queue_peer_init
2024/09/20 21:51:28 [debug] 45#45: *24 ngx_http_upstream_queue_peer_get
2024/09/20 21:51:28 [debug] 45#45: *24 peer.get = 0
2024/09/20 21:51:28 [debug] 45#45: *24 ngx_http_upstream_queue_peer_free
2024/09/20 21:51:28 [notice] 7#7: signal 17 (SIGCHLD) received from 45
2024/09/20 21:51:28 [alert] 7#7: worker process 45 exited on signal 11
```

If i turn off gzip in config file, all is work :
```
user  nginx;
worker_processes  auto;

error_log  /dev/stderr debug;
pid        /var/run/nginx.pid;

load_module /etc/nginx/modules/ngx_http_upstream_queue_module.so;

events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" ${request_time}s "$http_x_forwarded_for" $upstream_addr '
                      '$upstream_response_length ${upstream_connect_time}s ${upstream_header_time}s ${upstream_response_time}s $upstream_status';

    access_log  /dev/stdout  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    client_body_temp_path    /var/cache/nginx/client_temp;
    fastcgi_temp_path        /var/cache/nginx/fastcgi_temp;
    proxy_temp_path          /var/cache/nginx/proxy_temp;

    upstream backend {
        least_conn;
        server 127.0.0.1:8080 max_conns=25;
        queue 200;
    }

    server {
        listen 80 default_server;

        server_name  _;

        # Failed when enabled
        gzip on;
        gzip_min_length 1100;
        gzip_buffers 32 4k;
        gzip_types text/css text/scss text/plain text/xml application/xml application/json application/javascript;
        gzip_vary on;
        
        location / {
            proxy_pass http://backend;
        }
    }

    server_tokens off;
}
```

I built it with nginx 1.26 and 1.27 with same behaviour. Can this problem be solved?

Thank you for your help

**Comment by RekGRpth** [comment] 2024-09-21 07:25
Can't reproduce without knowing what the server 127.0.0.1:8080 is returning. Can you supplement the reproduction?

**Comment by vcazsdk** [comment] 2024-09-21 13:18
I'm sorry, after doing several tests, I realized that the error did not come from the gzip options, but the use of a variable.
In the configuration below, if I remove the queue line, no crash. With queue option, server crash :

```
user  nginx;
worker_processes  auto;

error_log  /dev/stderr debug;
pid        /var/run/nginx.pid;

load_module /etc/nginx/modules/ngx_http_upstream_queue_module.so;

events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" ${request_time}s "$http_x_forwarded_for" $upstream_addr '
                      '$upstream_response_length ${upstream_connect_time}s ${upstream_header_time}s ${upstream_response_time}s $upstream_status';

    access_log  /dev/stdout  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    client_body_temp_path    /var/cache/nginx/client_temp;
    fastcgi_temp_path        /var/cache/nginx/fastcgi_temp;
    proxy_temp_path          /var/cache/nginx/proxy_temp;

    upstream backend {
        least_conn;
        server 127.0.0.1:8080 max_conns=25;
        queue 200; # Crash if present
    }

    server {
        listen 80 default_server;

        server_name  _;

        gzip on;
        gzip_min_length 1100;
        gzip_buffers 32 4k;
        gzip_types text/css text/scss text/plain text/xml application/xml application/json application/javascript;
        gzip_vary on;

        set $var backend;

        location / {
            proxy_pass http://$var;
        }
    }

    server_tokens off;
}
```

**Comment by RekGRpth** [comment] 2024-09-21 14:31
Reproduced, studying...

**Comment by RekGRpth** [comment] 2024-09-21 15:29
fixed by https://github.com/RekGRpth/ngx_http_upstream_queue_module/commit/40cd174ff8914077064b21aa61fefe82d72a5eaa thanx for report!

**Closed by RekGRpth** 2024-09-21 15:29 UTC
